import { generatePollinationsUrl } from '@/lib/pollinations';
import ErrorLogger from '@/lib/ErrorLogger';

export interface SlideData {
    title: string;
    subtitle?: string;
    content: string[];
    image_prompt?: string;
    type: 'title' | 'content' | 'section';
}

export interface PresentationData {
    title: string;
    slides: SlideData[];
}

export async function createPresentation(data: PresentationData) {
    if (typeof window === 'undefined') {
        throw new Error('createPresentation must run in the browser');
    }
    let PptxGenJS: any;
    try {
        const mod = await import('pptxgenjs');
        PptxGenJS = mod.default || mod;
    } catch (err) {
        ErrorLogger.error('Failed to load pptxgenjs', err);
        throw new Error('Could not load presentation library');
    }

    // @ts-expect-error - Constructor type mismatch in some versions
    const pres = new PptxGenJS();

    // Set Metadata
    pres.title = data.title;
    pres.author = 'DUB5 Learning Platform';

    // Define a master slide for consistent branding
    pres.defineSlideMaster({
        title: 'MASTER_SLIDE',
        background: { color: 'FFFFFF' },
        objects: [
            {
                rect: { x: 0, y: 0, w: '100%', h: 0.15, fill: { color: 'FF0000' } } // Brand strip
            },
            {
                text: {
                    text: 'Generated by DUB5 AI',
                    options: { x: 0.5, y: '95%', w: '90%', align: 'center', fontSize: 10, color: 'AAAAAA' }
                }
            }
        ]
    });

    // Create Slides
    for (const slideData of data.slides) {
        const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

        if (slideData.type === 'title') {
            try {
                slide.addText(slideData.title, {
                    x: 1, y: 1.5, w: '80%', h: 1,
                    fontSize: 44, bold: true, color: '363636', align: 'center'
                });
                if (slideData.subtitle) {
                    slide.addText(slideData.subtitle, {
                        x: 1, y: 2.5, w: '80%', h: 1,
                        fontSize: 24, color: '757575', align: 'center'
                    });
                }
            } catch {}
        }
        else if (slideData.type === 'section') {
            slide.background = { color: 'EEF2FF' }; // Light blue for sections
            try {
                slide.addText(slideData.title, {
                    x: 1, y: '40%', w: '80%', h: 1,
                    fontSize: 36, bold: true, color: '1E3A8A', align: 'center'
                });
            } catch {}
        }
        else {
            // Content Slide
            try {
                slide.addText(slideData.title, {
                    x: 0.5, y: 0.5, w: '90%', h: 0.8,
                    fontSize: 32, bold: true, color: '363636'
                });
            } catch {}

            // Add bullet points
            const contentArray = Array.isArray(slideData.content) ? slideData.content : [];
            const bullets = contentArray.map(text => ({ text, options: { fontSize: 18, breakLine: true } }));

            // If there's an image, split layout
            if (slideData.image_prompt) {
                // Text on left
                try {
                    slide.addText(bullets, {
                        x: 0.5, y: 1.5, w: 4.5, h: 4,
                        color: '505050', bullet: true, lineSpacing: 28
                    });
                } catch {}

                // Image on right
                const imageUrl = generatePollinationsUrl(slideData.image_prompt, { width: 800, height: 600 });

                // try to fetch base64 to ensure it works offline/embedded
                try {
                    // For client-side generation, we can pass URL directly if CORS allows, 
                    // but Pollinations usually allows it. We'll try direct URL first for speed.
                    slide.addImage({
                        path: imageUrl,
                        x: 5.2, y: 1.5, w: 4.5, h: 3.5
                    });
                } catch {}
            } else {
                // Full width text
                try {
                    slide.addText(bullets, {
                        x: 0.5, y: 1.5, w: '90%', h: 4,
                        color: '505050', bullet: true, lineSpacing: 32
                    });
                } catch {}
            }
        }
    }

    return pres;
}
